### ISSUE TITLE
Cursor pointer not working

### ISSUE THREAD

**Issue by eWert-Online** [reasonml-labs/bs-css#179]
The `pointer` value can't be set on `cursor`. In fact none of the values i tried could be set. It returns the following error: 

```
We've found a bug for you!
  
  67 │       maxWidth(25->px),
  68 │       maxHeight(25->px),
  69 │       cursor(pointer),
  70 │     ]);
  71 │ };
  
  The value pointer can't be found
  
  Hint: Did you mean miter, filter, center or picker?
  
FAILED: subcommand failed.
>>>> Finish compiling(exit: 1)
```

**Comment by lucasweng** [comment]
Hi @eWert-Online ,

The constructor alias for ``[> | `pointer]`` is not provided in the interface yet (see `Css.rei`),  and that's why writing `cursor(pointer)` causes a compilation error saying `The value pointer can't be found`.

For now, you can use constructors directly, so ``cursor(`pointer)`` will work. 

Here are the constructors that can be set on `cursor`:
https://github.com/reasonml-labs/bs-css/blob/fa3518cdf38d9dbcd53a83db837c8fe241420166/src/Css_AtomicTypes.rei#L430-L468
