### ISSUE TITLE
How to use gridTemplateAreas()

### ISSUE THREAD

**Issue by cuevash** [reasonml-labs/bs-css#185]
Hi there,

First of all thanks so much for this cool library. I love it.

I am trying to use gridTemplateAreas but I am getting an error in the code below:

`
  open Css;

  let app =
    style([
      height(vh(100.0)),
      background(grey),
      position(relative),
      display(grid),
      gridTemplateColumns([pct(50.0), pct(50.0)]),
      gridTemplateRows([pct(50.0), pct(50.0)]),
      gridTemplateAreas(areas(['area1', 'area2')),
`
Error: Unbound value areas
Hint: Did you mean alias?

Still learning reasonml , so it could be a simple error..

**Comment by lucasweng** [comment]
Hi @cuevash,

The error occurs because there is no constructor alias for the `` `area`` in the interface file `Css_Core.rei`, while values like [`pct`](https://github.com/reasonml-labs/bs-css/blob/e14f4cc500be48989acd1e938cae9cebc54ab488/bs-css/src/Css_Core.rei#L1331) and [`grid`](https://github.com/reasonml-labs/bs-css/blob/e14f4cc500be48989acd1e938cae9cebc54ab488/bs-css/src/Css_Core.rei#L1413) have aliases, so we can write for example `pct(50.0)` instead of `` `percent(50.0)``. Aliases are handier 🙂 

For now, you can use the constructor `` `area`` directly like `` gridTemplateAreas(`areas(['area1', 'area2'))``,  and it should work fine.

**Comment by cuevash** [comment]
Thanks a lot!

**Comment by giraud** [comment]
alias added
